### ISSUE TITLE
broken display of language list

### ISSUE THREAD

**Issue by plegall** [modus75/piwigo-modus#2]
The language list, provided by plugin Language Switch is broken.

![modus-language-switch](https://cloud.githubusercontent.com/assets/9326959/6688848/d83f0600-ccb6-11e4-9dd3-188b34a7a1b0.png)

**Comment by modus75** [comment]
Do you have an online link ? Thanks

**Comment by plegall** [comment]
Let's take http://piwigo.us/beta/27/

**Comment by modus75** [comment]
I think it is a plugin issue rather than modus issue. The plugin should add
[class*="langflag-"] {
    overflow: hidden;
    text-indent: -9999px;
    vertical-align: bottom;
}

(rule already exists)
