### ISSUE TITLE
Photos not displayed in selected size

### ISSUE THREAD

**Issue by bpape** [modus75/piwigo-modus#7]
While viewing individual pictures in a gallery, the picture is displayed in size "Medium", regardless of the selected size in the "Photo sizes" menu (the selected photo size has a check mark before it).

When the "Photo sizes" menu is accessed and a different photo size is chosen, the photo is then re-displayed in that size, but when navigating to the next picture in the album, the photo is again shown in size "Medium".

This is a problem in Firefox 45.0 and Safari 9.0.

**Comment by modus75** [comment]
modus automatically choses the displayed photo to best match your window size. probably your screen with your chosen dimensions for medium are the closest ...

If you still think, it is an issue please open a discussion on the forum (I would also need a link)

**Comment by bpape** [comment]
Just to be clear, which forum are you referring to? The general piwigo forum (http://piwigo.org/forum/) ?

FYI, the display is an Apple 27-inch Retina display, resolution 5120 x 2880, and the browser window is maximized.  The sizes are defined (from Medium on up) as:
﻿ M - medium (792 x 527)
L - large (1008 x 671)
XL - extra large (1224 x 815)
✔ XXL - huge (1656 x 1103)

**Comment by modus75** [comment]
Yes that forum in the themes section. 
Please give a link because the behaviour you indicate is not the intended one. Also check if you have plug-ins such as automatic size installed.
